In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv('Insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [68]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [70]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(1)

In [72]:
df.drop_duplicates(inplace=True)

In [73]:
df.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [74]:
num_cols = df.select_dtypes(include=np.number).columns.tolist()
num_cols

['age', 'bmi', 'children', 'charges']

In [75]:

x=df.drop('charges', axis=1)
y = df['charges']

In [76]:
print("Shape of x:", x.shape)
print("Shape of y:", y.shape)

Shape of x: (1337, 6)
Shape of y: (1337,)

In [77]:
X = pd.get_dummies(
    x,
    columns=["sex", "smoker", "region"],
    dtype=int
)

In [78]:
X.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,1,0,0,1,0,0,0,1
1,18,33.770,1,0,1,1,0,0,0,1,0
2,28,33.000,3,0,1,1,0,0,0,1,0
3,33,22.705,0,0,1,1,0,0,1,0,0
4,32,28.880,0,0,1,1,0,0,1,0,0

In [79]:
X.dtypes

age                   int64
bmi                 float64
children              int64
sex_female            int64
sex_male              int64
smoker_no             int64
smoker_yes            int64
region_northeast      int64
region_northwest      int64
region_southeast      int64
region_southwest      int64
dtype: object

In [80]:
y.dtypes

dtype('float64')

In [81]:
print("Are all X columns numerical?")
print(np.all(X.dtypes.apply(lambda dtype: np.issubdtype(dtype, np.number))))

print("\nIs Y numerical?")
print(pd.api.types.is_numeric_dtype(Y.dtype))

print("\nMissing values in X:")
print(X.isnull().sum().sum())

print("\nMissing values in Y:")
print(y.isnull().sum())

Are all X columns numerical?
True

Is Y numerical?
True

Missing values in X:
0

Missing values in Y:
0